name: Telegram channel export

on:
  schedule:
    - cron: "0 * * * *"   # запуск каждый час
  workflow_dispatch:       # ручной запуск

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run export script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_LINK: ${{ secrets.CHANNEL_LINK }}
          EXCEL_FILE: ${{ secrets.EXCEL_FILE }}
        run: |
          python tg_channel_to_excel.py

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: channel_export
          path: ${{ secrets.EXCEL_FILE }}
